### PR TITLE
Add lambda conditional switch (LambdaConditionalSwitch)

### PR DESCRIPTION
**Pull request by akiller**
Hi,

I've added a lambda conditional switch because it would be super useful for my use case.

It allows you to pass in a list of lambdas and the widget from the first lambda which returns true is returned.

I guess I could have used the exiting ConditionalSwitch to do what I need by manipulating the variable passed to valueBuilder but this felt cleaner.

Thanks

### CODE REVIEW

**Comment by crizant** [comment]
Actually, I doubt if this package is still useful because you can achieve almost the same thing by using the new pattern-matching syntax:
https://dart.dev/language/patterns#switch-statements-and-expressions

**Comment by akiller** [comment]
> Actually, I doubt if this package is still useful because you can achieve almost the same thing by using the new pattern-matching syntax: [dart.dev/language/patterns#switch-statements-and-expressions](https://dart.dev/language/patterns#switch-statements-and-expressions)

Oh I hadn't seen that new syntax, thanks for the heads up.

However it doesn't look like you can use switch statements inside your widget builds, e.g. like this, which I guess it what this PR would help solve:

image

(it errors with error: Unexpected text 'case'. (unexpected_token at [xxxx] lib\xxxx:71))

**Comment by crizant** [comment]
> > Actually, I doubt if this package is still useful because you can achieve almost the same thing by using the new pattern-matching syntax: [dart.dev/language/patterns#switch-statements-and-expressions](https://dart.dev/language/patterns#switch-statements-and-expressions)
> 
> Oh I hadn't seen that new syntax, thanks for the heads up.
> 
> However it doesn't look like you can use switch statements inside your widget builds, e.g. like this, which I guess it what this PR would help solve:
> 
> image
> 
> (it errors with error: Unexpected text 'case'. (unexpected_token at [xxxx] lib\xxxx:71))

Yes you can, please take a look of my medium article:
https://medium.com/p/d4da53370e66

**Comment by akiller** [comment]
> Yes you can, please take a look of my medium article: [medium.com/p/d4da53370e66](https://medium.com/p/d4da53370e66)


Ahh I see, thank you. That seems really powerful.

I've tried to see if I can make that work for my use case and I'm sure I can because I need to evaluate conditions like this:

```dart
() => state.status == Status.loaded && state.users.isEmpty: (context) => Text('No users'),
() => state.status == Status.loaded && state.users.isNotEmpty: (context) => Text('Users')
() => state.status == Status.error && state.exception != null: (context) => Text('Exception')
```

I guess I could refactor my state objects to make them more compatible with how the switch expressions work though. But the code added in this pull request seems to satisfy what I need for the moment and keeps  it a little simpler

But yes I agree, using the built-in Dart tools where possible is much better

**Comment by crizant** [comment]
> > Yes you can, please take a look of my medium article: [medium.com/p/d4da53370e66](https://medium.com/p/d4da53370e66)
> 
> Ahh I see, thank you. That seems really powerful.
> 
> I've tried to see if I can make that work for my use case and I'm sure I can because I need to evaluate conditions like this:
> 
> ```dart
> () => state.status == Status.loaded && state.users.isEmpty: (context) => Text('No users'),
> () => state.status == Status.loaded && state.users.isNotEmpty: (context) => Text('Users')
> () => state.status == Status.error && state.exception != null: (context) => Text('Exception')
> ```
> 
> I guess I could refactor my state objects to make them more compatible with how the switch expressions work though. But the code added in this pull request seems to satisfy what I need for the moment and keeps it a little simpler
> 
> But yes I agree, using the built-in Dart tools where possible is much better

Combining with the new "record" feature, you can do something like:
```dart
final record = (state.status, state.users.isEmpty, state.exception);
return switch (record) {
  (Status.loaded, true, _) => Text('No users'),
  (Status.loaded, false, _) => Text('Users'),
  (Status.error, _, Exception) => Text('Exception'),
};
```
Just make sure you handle all cases or add a fallback condition.

**Comment by akiller** [comment]
That's really useful, thank you!

Dart/Flutter isn't my main language so it's easy to miss these new features they keep adding.

**Comment by crizant** [comment]
> That's really useful, thank you!
> 
> Dart/Flutter isn't my main language so it's easy to miss these new features they keep adding.

You are welcome. So I will close this issue now.

**Pull request closed without merging**
